http:
  host: 127.0.0.1
  port: 8080

grpc:
  host: 127.0.0.1
  port: 50051

postgres-prod:
  host: postgresql
  port: 5432
  user: postgres
  password: postgres
  db: skylang

postgres-dev:
  host: 127.0.0.1
  port: 5432
  user: postgres
  password: sa
  db: skylang

redis-dev:
  host: localhost
  port: 6379
  password: 1708
  db: 0

auth:
  secret-key: secret

email:
  password: ruqs4XdcvhndKnrEjkDi
  username: skylang@inbox.ru
  host: smtp.mail.ru
  port: 465